# Generated by Django 5.0.14 on 2026-06-11 02:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_leads', models.IntegerField(default=0)),
                ('new_leads', models.IntegerField(default=0)),
                ('qualified_leads', models.IntegerField(default=0)),
                ('meetings_booked', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('ai_interactions', models.IntegerField(default=0)),
                ('active_conversations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='businesses.business')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('business', 'date')},
            },
        ),
    ]
