# Lead Statuses
LEAD_STATUS_NEW = 'new'
LEAD_STATUS_CONTACTED = 'contacted'
LEAD_STATUS_QUALIFIED = 'qualified'
LEAD_STATUS_UNQUALIFIED = 'unqualified'
LEAD_STATUS_MEETING_BOOKED = 'meeting_booked'
LEAD_STATUS_WON = 'won'
LEAD_STATUS_LOST = 'lost'

LEAD_STATUSES = [
    LEAD_STATUS_NEW,
    LEAD_STATUS_CONTACTED,
    LEAD_STATUS_QUALIFIED,
    LEAD_STATUS_UNQUALIFIED,
    LEAD_STATUS_MEETING_BOOKED,
    LEAD_STATUS_WON,
    LEAD_STATUS_LOST,
]

# Lead Sources
LEAD_SOURCE_WEBSITE = 'website'
LEAD_SOURCE_REFERRAL = 'referral'
LEAD_SOURCE_SOCIAL = 'social'
LEAD_SOURCE_COLD_CALL = 'cold_call'
LEAD_SOURCE_ADVERTISEMENT = 'advertisement'
LEAD_SOURCE_OTHER = 'other'

# User Roles
ROLE_SUPER_ADMIN = 'super_admin'
ROLE_BUSINESS_OWNER = 'business_owner'
ROLE_STAFF = 'staff'

# Conversation Statuses
CONVERSATION_ACTIVE = 'active'
CONVERSATION_PAUSED = 'paused'
CONVERSATION_CLOSED = 'closed'
CONVERSATION_AI_HANDOFF = 'ai_handoff'

# Agent Statuses
AGENT_STATUS_PENDING = 'pending'
AGENT_STATUS_RUNNING = 'running'
AGENT_STATUS_COMPLETED = 'completed'
AGENT_STATUS_FAILED = 'failed'
AGENT_STATUS_PAUSED = 'paused'

# Score Ranges
SCORE_MIN = 0
SCORE_MAX = 100
SCORE_QUALIFIED_THRESHOLD = 50

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
