# Generated by Django 5.0.14 on 2026-06-11 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0007_alter_business_ai_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('sms', 'SMS (Twilio)'), ('email', 'Email'), ('slack', 'Slack'), ('discord', 'Discord'), ('instagram', 'Instagram DM'), ('facebook', 'Facebook Messenger')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_integrations', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'channel_type', 'name')},
            },
        ),
    ]
