# Generated by Django 5.0.14 on 2026-06-11 02:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('ai_handoff', 'AI Handoff')], default='active', max_length=20)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='web', max_length=20)),
                ('ai_paused', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('lead', 'Lead'), ('ai', 'AI'), ('staff', 'Staff'), ('system', 'System')], max_length=10)),
                ('sender_id', models.UUIDField(blank=True, null=True)),
                ('content', models.TextField()),
                ('channel', models.CharField(default='web', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
