# Generated by Django 5.0.14 on 2026-06-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ai_api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='business',
            name='ai_base_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='business',
            name='ai_max_tokens',
            field=models.IntegerField(default=1024),
        ),
        migrations.AddField(
            model_name='business',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='ai_provider',
            field=models.CharField(choices=[('mock', 'Mock (No LLM)'), ('openai', 'OpenAI'), ('openai_compatible', 'OpenAI-Compatible (OpenRouter, Together, Groq, etc.)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google Gemini'), ('mistral', 'Mistral AI'), ('local', 'Local LLM (Ollama, LM Studio, vLLM)')], default='mock', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='ai_temperature',
            field=models.FloatField(default=0.7),
        ),
    ]
