# Generated by Django 5.0.14 on 2026-06-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_ai_api_key_business_ai_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='ai_provider',
            field=models.CharField(choices=[('mock', 'Mock (No LLM)'), ('openai', 'OpenAI'), ('openai_compatible', 'OpenAI-Compatible (OpenRouter, Together, Groq, etc.)'), ('ollama', 'Ollama (Local AI)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google Gemini'), ('mistral', 'Mistral AI'), ('local', 'Local LLM (LM Studio, vLLM, etc.)')], default='mock', max_length=30),
        ),
    ]
